### ISSUE TITLE
InvalidAuthenticationToken是什么原因啊

### ISSUE THREAD

**Issue by shentam** [merrycodes/Office-E5#6]
[Some information was truncated for brevity, enable debug logging for more details]
Error: Exception in thread "main" com.microsoft.graph.http.GraphServiceException: Error code: InvalidAuthenticationToken
Error message: CompactToken parsing failed with error code: [80](https://github.com/shentam/Office-E5/runs/7695248408?check_suite_focus=true#step:5:81)049217

GET https://graph.microsoft.com/v1.0/me
SdkVersion : graph-java/v2.5.0
Authorization : [PII_REDACTED]

401 : Unauthorized
[...]

[Some information was truncated for brevity, enable debug logging for more details]
	at com.microsoft.graph.http.GraphServiceException.createFromConnection(GraphServiceException.java:501)
	at com.microsoft.graph.http.CoreHttpProvider.handleErrorResponse(CoreHttpProvider.java:503)
	at com.microsoft.graph.http.CoreHttpProvider.sendRequestInternal(CoreHttpProvider.java:423)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:220)
	at com.microsoft.graph.http.CoreHttpProvider.send(CoreHttpProvider.java:200)
	at com.microsoft.graph.http.BaseRequest.send(BaseRequest.java:345)
	at com.microsoft.graph.requests.extensions.UserRequest.get(UserRequest.java:175)
	at com.merrycodes.Main.main(Main.java:37)
Error: Process completed with exit code 1.

**Comment by merrycodes** [comment]
项目 `Setting` 中是否有把对应的字段填写正确，如果正确检查一下 `CLIENT_SECRET` 以及 `Azure` 的账号密码
